# Lab-1

## Learning the XOR Boolean Function Using an MLP

Create the Dataset

In [1]:
import numpy as np

In [2]:
X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])

y = np.array([[0],
              [1],
              [1],
              [0]])

Here, x contains all 4 inputs combinations and y contains the XOR outputs and this is not linearly separable so we need hidden layer.

### Implementation - 1 using Keras

In [3]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

Sequential for the layer-by-layer neural network

Dense represents a fully connected layer and each neuron is connected to all neurons of previous layer

Adam is an optimizer which used for changes the weights effectively.

Model with ReLU activation

In [4]:
model_relu = Sequential([
    Dense(2, input_dim=2, activation='relu'),
    Dense(1, activation='sigmoid')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


First Dense

-For Dense, we're taking as 2 because XOR requires at least 2 neurons to create the on-linear separation, with 1 neuron XOR cannot be learned.

-Input_dim=2 becasue we have 2 inputs X1, X2.

-Activation='relu' mense use the ReLU as a activation function, it perform fast computation, it avoids vanishing gradient.

Second Dense

-This is output layer and out output is binary so we need only one output neuron.

-And we are using sigmoid because it's very good for the binary classification

In [5]:
model_relu.compile(
    loss='binary_crossentropy',
    optimizer=Adam(learning_rate=0.1),
    metrics=['accuracy']
)

We are using Adam optimizer because it combines momentum and adaptive learning Rate and it also very effective for the small dataset.

In [6]:
history_relu = model_relu.fit(X, y, epochs=500, verbose=0)
print(history_relu)

Model with Tanh activation

In [7]:
model_tanh = Sequential([
    Dense(2, input_dim=2, activation='tanh'),
    Dense(1, activation='sigmoid')
])

In [8]:
model_tanh.compile(
    loss='binary_crossentropy',
    optimizer=Adam(learning_rate=0.1),
    metrics=['accuracy']
)

In [9]:
history_tanh = model_tanh.fit(X, y, epochs=500, verbose=1)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.7500 - loss: 0.7615
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.7500 - loss: 0.7015
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.7500 - loss: 0.6596
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.7500 - loss: 0.6350
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.7500 - loss: 0.6233
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.7500 - loss: 0.6173
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.7500 - loss: 0.6119
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.7500 - loss: 0.6052
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.7500 - loss: 0.5970
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.7500 - loss: 0.5882
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.7500 - loss: 0.5794
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.7500 - loss

verbose=1 shows training progress for every epoch, including loss and accuracy. It helps us understand whether the model is learning but we usually keep verbose=0 to avoid cluttered output.

In [10]:
predictions = model_tanh.predict(X)
print(np.round(predictions))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 181ms/step
[[0.]
 [1.]
 [0.]
 [1.]]


In [11]:
predictions = model_relu.predict(X)
print(np.round(predictions))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 179ms/step
[[1.]
 [1.]
 [0.]
 [0.]]


We used an MLP with one hidden layer of two neurons. ReLU and Tanh were tested to study non-linearity. Binary cross-entropy with Adam optimizer was used for efficient learning, and sigmoid activation was used in the output layer for binary classification.

### Implementation-2 using PyTorch

In [12]:
import torch
import torch.nn as nn
import torch.optim as optim

In [13]:
X_torch = torch.FloatTensor(X)
y_torch = torch.FloatTensor(y)

PyTorch is work with the tensors only that's why we need to conver that.

And here we're convert that into the FloatTensor because neural network use floating-point math, integers tensors cannot store the gradients properly

In [14]:
class XORNet(nn.Module):
  def __init__(self, activation='relu'):
    super(XORNet, self).__init__()
    self.fc1 = nn.Linear(2, 2) # Hidden layer 2-input features, 2-number of neurons
    self.fc2 = nn.Linear(2, 1) # Output layer 2-from hidden layer, Single binary output
    self.activation = activation

  def forward(self, x):
    if self.activation == 'relu':
      x = torch.relu(self.fc1(x)) # adds non-linearity
    else:
      x = torch.tanh(self.fc1(x)) # adds non-linearity
    x = torch.sigmoid(self.fc2(x)) # Converts output to probability (0–1) which is require for binary classification
    return x

Every PyTorch model is a class and nn.Module is the base class for all Neural Netwokrs, it's similar to the sequential but more flexible than that.

In above forward is define how data flows through the network and automatically used that during the training and prediction

In [15]:
model = XORNet(activation='tanh')
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.1)

In [16]:
for epochs in range(1000):
  optimizer.zero_grad() # Clears old gradients & Prevents gradient accumulation
  output = model(X_torch)
  loss = criterion(output, y_torch)
  loss.backward()
  optimizer.step()

In [17]:
with torch.no_grad(): # Disables gradient tracking
  print(torch.round(model(X_torch))) # round use for convert op to 0 or 1.

tensor([[0.],
        [0.],
        [1.],
        [1.]])


In PyTorch, we manually defined the network architecture, forward pass, loss function, optimizer, and training loop. This gave us full control over backpropagation and parameter updates, helping us understand how neural networks learn the XOR function

### Implementation - 3 using Tensor-Flow (Low-Level API)

In [18]:
import tensorflow as tf

In [19]:
W1 = tf.Variable(tf.random.normal([2, 2]))  # Hidden layer weight matrix 2-input features, 2-number of hidden neurons
b1 = tf.Variable(tf.zeros([2]))             # One bias for each hidden neuron, initialized to zero
W2 = tf.Variable(tf.random.normal([2, 1]))  # 2-from hidden layer, 1-single output neuron
b2 = tf.Variable(tf.zeros([1]))             # Bias for output neuron

W-weights  b-biases

tf.random.normal - Allows neurons to learn different features

In [20]:
optimizer = tf.optimizers.Adam(0.1)

optimizers updates weights using gradients and minimizes loss

In [21]:
tf.random.set_seed(0)

This makes weight initialization reproducible

Produce the same output for every run

But without this it gives different output for each run

In [22]:
X = tf.constant(X, dtype=tf.float32)
y = tf.constant(y, dtype=tf.float32)

TensorFlow operations require tensors

In [23]:
for epoch in range(1000):
    with tf.GradientTape() as tape:
        h = tf.tanh(tf.matmul(X, W1) + b1)
        y_pred = tf.sigmoid(tf.matmul(h, W2) + b2)
        # loss calculation
        loss = tf.reduce_mean(
            tf.keras.losses.binary_crossentropy(y, y_pred)
        )
    # Computes partial derivatives
    grads = tape.gradient(loss, [W1, b1, W2, b2])
    # Uses gradients to update weights (Learning is happening here)
    optimizer.apply_gradients(zip(grads, [W1, b1, W2, b2]))

GradientTape - Records all operations, automatically compute the gradient, enable backpropogation

matmul - matrix multiplication

In [24]:
print(tf.round(y_pred))

tf.Tensor(
[[0.]
 [1.]
 [1.]
 [0.]], shape=(4, 1), dtype=float32)


In TensorFlow low-level implementation, we manually defined weights, forward pass, loss calculation, gradient computation, and parameter updates using GradientTape, which helped us understand the internal working of backpropagation while learning the XOR function.